---

# **EDA Session 01 Assignment**

Welcome to your first Exploratory Data Analysis (EDA) assignment! This assignment will help you practice the fundamental Pandas concepts you've learned. You will be working with the same dataset used in the notebook.

## **Dataset Information**

**Source:** Google Sheets
**URL:** `https://docs.google.com/spreadsheets/d/1zLGcNoattvIPSjkHYF9lzn6R_kGxGWqC/export?format=csv`

Before you begin, make sure you have loaded the dataset into a Pandas DataFrame named `data` as shown in the notebook.

In [22]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/1zLGcNoattvIPSjkHYF9lzn6R_kGxGWqC/export?format=csv"

data = pd.read_csv(url)

data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

## **Task 1: Load and Explore the Dataset**

**Instructions:**

1.  Load the dataset from the provided URL into a Pandas DataFrame. Name your DataFrame `data`.
2.  Display the first 5 rows of the `data` DataFrame.
3.  Display the last 3 rows of the `data` DataFrame.
4.  Print the shape (number of rows and columns) of the DataFrame.
5.  Get a concise summary of the DataFrame, including the data types and non-null values for each column.
6.  Generate descriptive statistics for only the numerical columns in the DataFrame.

**URL:** `https://docs.google.com/spreadsheets/d/1zLGcNoattvIPSjkHYF9lzn6R_kGxGWqC/export?format=csv`

In [21]:
# First 5 rows
print(data.head())

# Last 3 rows
print(data.tail(3))

# Shape
print(data.shape)

# Data Information
data.info()

# Numerical Statistics
print(data.describe())

  transaction_id StockCode                            item_name  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1         536365     71053                  WHITE METAL LANTERN
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.

   order_quantity transaction_date  item_price  CustomerID         Country
0               6     12/1/10 8:26        2.55     17850.0  United Kingdom
1               6     12/1/10 8:26        3.39     17850.0  United Kingdom
2               8     12/1/10 8:26        2.75     17850.0  United Kingdom
3               6     12/1/10 8:26        3.39     17850.0  United Kingdom
4               6     12/1/10 8:26        3.39     17850.0  United Kingdom
       transaction_id StockCode                        item_name  \
541906         581587     23254    CHILDRENS CUTLERY DOLLY GIRL
541907         581587     23255  CHILDRENS CUTLERY CIRCUS PARADE
541908         581587     22138    BAKING SET 9 PIECE RETROSPOT

        order_quantity transaction_date  item_price  CustomerID Country
541906               4    12/9/11 12:50        4.15     12680.0  France
541907               4    12/9/11 12:50        4.15     12680.0  France
541908               3    12/9/11 12:50        4.95     12680.0  France
(541909, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    541909 non-null  object
 1   StockCode         541909 non-null  object
 2   item_name         540455 non-null  object
 3   order_quantity    541909 non-null  int64
 4   transaction_date  541909 non-null  object
 5   item_price        541909 non-null  float64
 6   CustomerID        406829 non-null  float64
 7   Country           541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB
       order_quantity     item_price     CustomerID
count   541909.000000  541909.000000  406829.000000
mean         9.552250       4.611114   15287.690570
std        218.081158      96.759853    1713.600303
min     -80995.000000  -11062.060000   12346.000000
25%          1.000000       1.250000   13953.000000
50%          3.000000       2.080000   15152.000000
75%         10.000000       4.130000   16791.000000
max      80995.000000   38970.000000   18287.000000

## **Task 2: Understand Columns and Data Types**

**Instructions:**

1.  Print all the column names of the `data` DataFrame.
2.  Display the data types of each column in the `data` DataFrame.
3.  Generate descriptive statistics for *all* columns (including object/categorical columns) in the `data` DataFrame.

In [20]:
# Column Names
print(data.columns)

# Data Types
print(data.dtypes)

# Statistics of all columns
print(data.describe(include='all'))

Index(['transaction_id', 'StockCode', 'item_name', 'order_quantity',
       'transaction_date', 'item_price', 'CustomerID', 'Country'],
      dtype='object')
transaction_id       object
StockCode            object
item_name            object
order_quantity        int64
transaction_date     object
item_price          float64
CustomerID          float64
Country              object
dtype: object
       transaction_id StockCode                           item_name  \
count          541909    541909                              540455
unique          25900      4070                                4223
top            573585    85123A  WHITE HANGING HEART T-LIGHT HOLDER
freq             1114      2313                                2369
mean              NaN       NaN                                 NaN
std               NaN       NaN                                 NaN
min               NaN       NaN                                 NaN
25%               NaN       NaN                                 NaN
50%               NaN       NaN                                 NaN
75%               NaN       NaN                                 NaN
max               NaN       NaN                                 NaN

        order_quantity transaction_date     item_price     CustomerID  \
count    541909.000000           541909  541909.000000  406829.000000
unique             NaN            23260            NaN            NaN
top                NaN   10/31/11 14:41            NaN            NaN
freq               NaN             1114            NaN            NaN
mean          9.552250              NaN       4.611114   15287.690570
std         218.081158              NaN      96.759853    1713.600303
min      -80995.000000              NaN  -11062.060000   12346.000000
25%           1.000000              NaN       1.250000   13953.000000
50%           3.000000              NaN       2.080000   15152.000000
75%          10.000000              NaN       4.130000   16791.000000
max       80995.000000              NaN   38970.000000   18287.000000

               Country
count           541909
unique              38
top     United Kingdom
freq            495478
mean               NaN
std                NaN
min                NaN
25%                NaN
50%                NaN
75%                NaN
max                NaN

## **Task 3: Rename Columns**

**Instructions:**

1.  Create a dictionary to rename the following columns in your `data` DataFrame:
    *   `'InvoiceNo'` to `'transaction_id'`
    *   `'Description'` to `'item_name'`
    *   `'Quantity'` to `'order_quantity'`
    *   `'UnitPrice'` to `'item_price'`
    *   `'InvoiceDate'` to `'transaction_date'`
2.  Apply these renames to the `data` DataFrame and make sure the changes are saved to `data`.
3.  Display the first 5 rows of the DataFrame to confirm the column names have been updated.

In [19]:
rename_columns = {
    "InvoiceNo": "transaction_id",
    "Description": "item_name",
    "Quantity": "order_quantity",
    "UnitPrice": "item_price",
    "InvoiceDate": "transaction_date"
}

data.rename(columns=rename_columns, inplace=True)

data.head()

,transaction_id,StockCode,item_name,order_quantity,transaction_date,item_price,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

## **Task 4: Data Selection and Filtering**

**Instructions:**

1.  Using `loc`, select and display the `item_name` and `item_price` columns for the first 10 rows of the `data` DataFrame.
2.  Filter the `data` DataFrame to show only orders where the `order_quantity` is greater than 1. Display the first 5 rows of this filtered DataFrame.
3.  Filter the `data` DataFrame to show orders where the `item_name` is 'WHITE HANGING HEART T-LIGHT HOLDER' **AND** the `order_quantity` is 6. Display all rows that meet this condition.
4.  Filter the `data` DataFrame to show orders where the `item_name` is 'WHITE METAL LANTERN' **OR** the `item_price` is less than 5. Display the first 5 rows of this filtered DataFrame.
5.  Using `iloc`, select and display all rows and only the first three columns of the `data` DataFrame.

In [18]:
# item_name and item_price for first 10 rows
print(data.loc[:9, ["item_name", "item_price"]])

# order_quantity > 1
print(data[data["order_quantity"] > 1].head())

# item_name = WHITE HANGING HEART T-LIGHT HOLDER AND quantity = 6
print(data[
    (data["item_name"] == "WHITE HANGING HEART T-LIGHT HOLDER") &
    (data["order_quantity"] == 6)
])

# item_name = WHITE METAL LANTERN OR item_price < 5
print(data[
    (data["item_name"] == "WHITE METAL LANTERN") |
    (data["item_price"] < 5)
].head())

# First three columns using iloc
print(data.iloc[:, :3])

                             item_name  item_price
0   WHITE HANGING HEART T-LIGHT HOLDER        2.55
1                  WHITE METAL LANTERN        3.39
2       CREAM CUPID HEARTS COAT HANGER        2.75
3  KNITTED UNION FLAG HOT WATER BOTTLE        3.39
4       RED WOOLLY HOTTIE WHITE HEART.        3.39
5         SET 7 BABUSHKA NESTING BOXES        7.65
6    GLASS STAR FROSTED T-LIGHT HOLDER        4.25
7               HAND WARMER UNION JACK        1.85
8            HAND WARMER RED POLKA DOT        1.85
9        ASSORTED COLOUR BIRD ORNAMENT        1.69
  transaction_id StockCode                            item_name  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1         536365     71053                  WHITE METAL LANTERN
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.

   order_quantity transaction_date  item_price  CustomerID         Country
0               6     12/1/10 8:26        2.55     17850.0  United Kingdom
1               6     12/1/10 8:26        3.39     17850.0  United Kingdom
2               8     12/1/10 8:26        2.75     17850.0  United Kingdom
3               6     12/1/10 8:26        3.39     17850.0  United Kingdom
4               6     12/1/10 8:26        3.39     17850.0  United Kingdom
       transaction_id StockCode                           item_name  \
0              536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER
49             536373    85123A  WHITE HANGING HEART T-LIGHT HOLDER
66             536375    85123A  WHITE HANGING HEART T-LIGHT HOLDER
278            536396    85123A  WHITE HANGING HEART T-LIGHT HOLDER
935            536502    85123A  WHITE HANGING HEART T-LIGHT HOLDER
...               ...       ...                                 ...
533124         581014    85123A  WHITE HANGING HEART T-LIGHT HOLDER
534570         581163    85123A  WHITE HANGING HEART T-LIGHT HOLDER
534876         581174    85123A  WHITE HANGING HEART T-LIGHT HOLDER
537852         581356    85123A  WHITE HANGING HEART T-LIGHT HOLDER
540217         581472    85123A  WHITE HANGING HEART T-LIGHT HOLDER

        order_quantity transaction_date  item_price  CustomerID  \
0                    6     12/1/10 8:26        2.55     17850.0
49                   6     12/1/10 9:02        2.55     17850.0
66                   6     12/1/10 9:32        2.55     17850.0
278                  6    12/1/10 10:51        2.55     17850.0
935                  6    12/1/10 12:36        2.95     16552.0
...                ...              ...         ...         ...
533124               6     12/7/11 9:34        2.95     16458.0
534570               6    12/7/11 14:34        2.95     12747.0
534876               6    12/7/11 15:08        2.95     13769.0
537852               6    12/8/11 12:28        2.95     17830.0
540217               6    12/8/11 19:55        2.95     15796.0

               Country
0       United Kingdom
49      United Kingdom
66      United Kingdom
278     United Kingdom
935     United Kingdom
...                ...
533124  United Kingdom
534570  United Kingdom
534876  United Kingdom
537852  United Kingdom
540217  United Kingdom

[559 rows x 8 columns]
  transaction_id StockCode                            item_name  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1         536365     71053                  WHITE METAL LANTERN
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.

   order_quantity transaction_date  item_price  CustomerID         Country
0               6     12/1/10 8:26        2.55     17850.0  United Kingdom
1               6     12/1/10 8:26        3.39     17850.0  United Kingdom
2               8     12/1/10 8:26        2.75     17850.0  United Kingdom
3               6     12/1/10 8:26        3.39     17850.0  United Kingdom
4               6     12/1/10 8:26        3.39     17850.0  United Kingdom
       transaction_id StockCode                            item_name
0              536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1              536365     71053                  WHITE METAL LANTERN
2              536365    84406B       CREAM CUPID HEARTS COAT HANGER
3              536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4              536365    84029E       RED WOOLLY HOTTIE WHITE HEART.
...               ...       ...                                  ...
541904         581587     22613          PACK OF 20 SPACEBOY NAPKINS
541905         581587     22899         CHILDREN'S APRON DOLLY GIRL
541906         581587     23254        CHILDRENS CUTLERY DOLLY GIRL
541907         581587     23255      CHILDRENS CUTLERY CIRCUS PARADE
541908         581587     22138        BAKING SET 9 PIECE RETROSPOT

[541909 rows x 3 columns]

## **Task 5: Sorting and Unique Values Analysis**

**Instructions:**

1.  Sort the `data` DataFrame by the `item_price` column in ascending order. Display the first 5 rows of the sorted DataFrame.
2.  Sort the `data` DataFrame by the `order_quantity` column in descending order. Display the first 5 rows of the sorted DataFrame.
3.  Find and print the number of unique values in the `item_name` column.
4.  Display all the unique values (product names) present in the `item_name` column.
5.  Find and print the number of unique values in the `Country` column.

In [17]:
# Sort by item_price
print(data.sort_values(by="item_price").head())

# Sort by order_quantity descending
print(data.sort_values(by="order_quantity", ascending=False).head())

# Number of unique item names
print(data["item_name"].nunique())

# All unique item names
print(data["item_name"].unique())

# Number of unique countries
print(data["Country"].nunique())

       transaction_id StockCode                      item_name  \
299983        A563186         B                Adjust bad debt
299984        A563187         B                Adjust bad debt
313647         564530     22678  FRENCH BLUE METAL DOOR SIGN 3
115808         546140     21527                        damages
516189         579880     22947                            NaN

        order_quantity transaction_date  item_price  CustomerID  \
299983               1    8/12/11 14:51   -11062.06         NaN
299984               1    8/12/11 14:52   -11062.06         NaN
313647               3    8/25/11 14:57        0.00         NaN
115808             -30     3/9/11 16:35        0.00         NaN
516189               5   11/30/11 17:14        0.00         NaN

               Country
299983  United Kingdom
299984  United Kingdom
313647  United Kingdom
115808  United Kingdom
516189  United Kingdom
       transaction_id StockCode                          item_name  \
540421         581483     23843        PAPER CRAFT , LITTLE BIRDIE
61619          541431     23166     MEDIUM CERAMIC TOP STORAGE JAR
502122         578841     84826     ASSTD DESIGN 3D PAPER STICKERS
74614          542504     37413                                NaN
421632         573008     84077  WORLD WAR 2 GLIDERS ASSTD DESIGNS

        order_quantity transaction_date  item_price  CustomerID  \
540421           80995     12/9/11 9:15        2.08     16446.0
61619            74215    1/18/11 10:01        1.04     12346.0
502122           12540   11/25/11 15:57        0.00     13256.0
74614             5568    1/28/11 12:03        0.00         NaN
421632            4800   10/27/11 12:26        0.21     12901.0

               Country
540421  United Kingdom
61619   United Kingdom
502122  United Kingdom
74614   United Kingdom
421632  United Kingdom
4223
['WHITE HANGING HEART T-LIGHT HOLDER' 'WHITE METAL LANTERN'
 'CREAM CUPID HEARTS COAT HANGER' ... 'lost'
 'CREAM HANGING HEART T-LIGHT HOLDER' 'PAPER CRAFT , LITTLE BIRDIE']
38

---

## **Submission**

Once you have completed all tasks, save your notebook and prepare it for submission as .ipynb file